---
kind: pipeline
type: docker
name: python-3-8

platform:
  os: linux
  arch: amd64

steps:
- name: Install package and test
  image: python:3.8
  commands:
  - test "$(md5sum tasks.py)" = "18f864b3ac76119938e3317e49b4ffa1  tasks.py"
  - pip install -U setuptools wheel pip; pip install invoke
  - invoke prepare-upload

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    token: 9ea10e04-a71a-4eea-9dcc-8eaabe1479e2

trigger:
  event:
  - pull_request
  - push
  - tag

---
kind: pipeline
type: docker
name: python-3-9

platform:
  os: linux
  arch: amd64

steps:
- name: Install package and test
  image: python:3.9
  commands:
  - test "$(md5sum tasks.py)" = "18f864b3ac76119938e3317e49b4ffa1  tasks.py"
  - pip install -U setuptools wheel pip; pip install invoke
  - invoke prepare-upload

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    token: 9ea10e04-a71a-4eea-9dcc-8eaabe1479e2

trigger:
  event:
  - pull_request
  - push
  - tag

---
kind: pipeline
type: docker
name: Deploy on Pypi

platform:
  os: linux
  arch: amd64

steps:
- name: Install twine and deploy
  image: python:3.8
  commands:
  - test "$(md5sum tasks.py)" = "18f864b3ac76119938e3317e49b4ffa1  tasks.py"
  - pip install -U setuptools wheel pip; pip install invoke
  - invoke upload --pypi-user "$pypi_username" --pypi-password "$pypi_password"
  environment:
    pypi_password:
      from_secret: pypi_password
    pypi_username:
      from_secret: pypi_username

trigger:
  event:
  - tag

depends_on:
- python-3-8
- python-3-9

---
kind: signature
hmac: 9a24ccae6182723af71257495d7843fd40874006c5e867cdebf363f497ddb839

...
